use super::*;

macro_rules! define_properties {
    (
        $(
            $(#[$meta:meta])*
            $name:literal: $property:ident($value:ty $(, $vp:ty)?),
        )+
    ) => {
        #[derive(Debug, PartialEq)]
        pub enum PropertyId<'a> {
            $(
                $(#[$meta])*
                $property$(($vp))?,
            )+
            All,
            Unparsed,
            Custom(&'a str),
        }

        #[derive(Debug, PartialEq)]
        pub enum Declaration<'a> {
            $(
                $(#[$meta])*
                $property($value $(, $vp)?),
            )+
            All(CSSWideKeyword),
            Unparsed(Box<'a, UnparsedProperty<'a>>),
            Custom(Box<'a, CustomProperty<'a>>),
        }
    };
}

#[derive(Debug, PartialEq)]
pub enum Prefix {
    None,
    WebKit,
    Moz,
    Ms,
    O,
}

pub type VendorPrefix<'a> = Vec<'a, Prefix>;

#[derive(Debug, PartialEq)]
pub enum BlendMode {
    Normal,
    Multiply,
    Screen,
    Overlay,
    Darken,
    Lighten,
    ColorDodge,
    ColorBurn,
    HardLight,
    SoftLight,
    Difference,
    Exclusion,
    Hue,
    Saturation,
    Color,
    Luminosity,
    PlusDarker,
    PlusLighter,
}

define_properties! {
    "background-color": BackgroundColor(Box<'a, CssColor<'a>>),
    "background-image": BackgroundImage(Vec<'a, Image<'a>>),
    "background-position-x": BackgroundPositionX(Vec<'a, PositionComponentFor_HorizontalPositionKeyword<'a>>),
    "background-position-y": BackgroundPositionY(Vec<'a, PositionComponentFor_VerticalPositionKeyword<'a>>),
    "background-position": BackgroundPosition(Vec<'a, BackgroundPosition<'a>>),
    "background-size": BackgroundSize(Vec<'a, BackgroundSize<'a>>),
    "background-repeat": BackgroundRepeat(Vec<'a, BackgroundRepeat>),
    "background-attachment": BackgroundAttachment(Vec<'a, BackgroundAttachment>),
    "background-clip": BackgroundClip(Vec<'a, BackgroundClip>, VendorPrefix<'a>),
    "background-origin": BackgroundOrigin(Vec<'a, BackgroundOrigin>),
    "background": Background(Vec<'a, Background<'a>>),
    "box-shadow": BoxShadow(Vec<'a, BoxShadow<'a>>, VendorPrefix<'a>),
    "opacity": Opacity(f64),
    "color": Color(Box<'a, CssColor<'a>>),
    "display": Display(Box<'a, Display<'a>>),
    "visibility": Visibility(Visibility),
    "width": Width(Box<'a, Size<'a>>),
    "height": Height(Box<'a, Size<'a>>),
    "min-width": MinWidth(Box<'a, Size<'a>>),
    "min-height": MinHeight(Box<'a, Size<'a>>),
    "max-width": MaxWidth(Box<'a, MaxSize<'a>>),
    "max-height": MaxHeight(Box<'a, MaxSize<'a>>),
    "block-size": BlockSize(Box<'a, Size<'a>>),
    "inline-size": InlineSize(Box<'a, Size<'a>>),
    "min-block-size": MinBlockSize(Box<'a, Size<'a>>),
    "min-inline-size": MinInlineSize(Box<'a, Size<'a>>),
    "max-block-size": MaxBlockSize(Box<'a, MaxSize<'a>>),
    "max-inline-size": MaxInlineSize(Box<'a, MaxSize<'a>>),
    "box-sizing": BoxSizing(BoxSizing, VendorPrefix<'a>),
    "aspect-ratio": AspectRatio(Box<'a, AspectRatio<'a>>),
    "overflow": Overflow(Box<'a, Overflow>),
    "overflow-x": OverflowX(OverflowKeyword),
    "overflow-y": OverflowY(OverflowKeyword),
    "text-overflow": TextOverflow(TextOverflow, VendorPrefix<'a>),
    "position": Position(Box<'a, Position2<'a>>),
    "top": Top(Box<'a, LengthPercentageOrAuto<'a>>),
    "bottom": Bottom(Box<'a, LengthPercentageOrAuto<'a>>),
    "left": Left(Box<'a, LengthPercentageOrAuto<'a>>),
    "right": Right(Box<'a, LengthPercentageOrAuto<'a>>),
    "inset-block-start": InsetBlockStart(Box<'a, LengthPercentageOrAuto<'a>>),
    "inset-block-end": InsetBlockEnd(Box<'a, LengthPercentageOrAuto<'a>>),
    "inset-inline-start": InsetInlineStart(Box<'a, LengthPercentageOrAuto<'a>>),
    "inset-inline-end": InsetInlineEnd(Box<'a, LengthPercentageOrAuto<'a>>),
    "inset-block": InsetBlock(Box<'a, InsetBlock<'a>>),
    "inset-inline": InsetInline(Box<'a, InsetInline<'a>>),
    "inset": Inset(Box<'a, Inset<'a>>),
    "border-spacing": BorderSpacing(Box<'a, Size2DFor_Length<'a>>),
    "border-top-color": BorderTopColor(Box<'a, CssColor<'a>>),
    "border-bottom-color": BorderBottomColor(Box<'a, CssColor<'a>>),
    "border-left-color": BorderLeftColor(Box<'a, CssColor<'a>>),
    "border-right-color": BorderRightColor(Box<'a, CssColor<'a>>),
    "border-block-start-color": BorderBlockStartColor(Box<'a, CssColor<'a>>),
    "border-block-end-color": BorderBlockEndColor(Box<'a, CssColor<'a>>),
    "border-inline-start-color": BorderInlineStartColor(Box<'a, CssColor<'a>>),
    "border-inline-end-color": BorderInlineEndColor(Box<'a, CssColor<'a>>),
    "border-top-style": BorderTopStyle(LineStyle),
    "border-bottom-style": BorderBottomStyle(LineStyle),
    "border-left-style": BorderLeftStyle(LineStyle),
    "border-right-style": BorderRightStyle(LineStyle),
    "border-block-start-style": BorderBlockStartStyle(LineStyle),
    "border-block-end-style": BorderBlockEndStyle(LineStyle),
    "border-inline-start-style": BorderInlineStartStyle(LineStyle),
    "border-inline-end-style": BorderInlineEndStyle(LineStyle),
    "border-top-width": BorderTopWidth(Box<'a, BorderSideWidth<'a>>),
    "border-bottom-width": BorderBottomWidth(Box<'a, BorderSideWidth<'a>>),
    "border-left-width": BorderLeftWidth(Box<'a, BorderSideWidth<'a>>),
    "border-right-width": BorderRightWidth(Box<'a, BorderSideWidth<'a>>),
    "border-block-start-width": BorderBlockStartWidth(Box<'a, BorderSideWidth<'a>>),
    "border-block-end-width": BorderBlockEndWidth(Box<'a, BorderSideWidth<'a>>),
    "border-inline-start-width": BorderInlineStartWidth(Box<'a, BorderSideWidth<'a>>),
    "border-inline-end-width": BorderInlineEndWidth(Box<'a, BorderSideWidth<'a>>),
    "border-top-left-radius": BorderTopLeftRadius(Box<'a, Size2DFor_DimensionPercentageFor_LengthValue<'a>>, VendorPrefix<'a>),
    "border-top-right-radius": BorderTopRightRadius(Box<'a, Size2DFor_DimensionPercentageFor_LengthValue<'a>>, VendorPrefix<'a>),
    "border-bottom-left-radius": BorderBottomLeftRadius(Box<'a, Size2DFor_DimensionPercentageFor_LengthValue<'a>>, VendorPrefix<'a>),
    "border-bottom-right-radius": BorderBottomRightRadius(Box<'a, Size2DFor_DimensionPercentageFor_LengthValue<'a>>, VendorPrefix<'a>),
    "border-start-start-radius": BorderStartStartRadius(Box<'a, Size2DFor_DimensionPercentageFor_LengthValue<'a>>),
    "border-start-end-radius": BorderStartEndRadius(Box<'a, Size2DFor_DimensionPercentageFor_LengthValue<'a>>),
    "border-end-start-radius": BorderEndStartRadius(Box<'a, Size2DFor_DimensionPercentageFor_LengthValue<'a>>),
    "border-end-end-radius": BorderEndEndRadius(Box<'a, Size2DFor_DimensionPercentageFor_LengthValue<'a>>),
    "border-radius": BorderRadius(Box<'a, BorderRadius<'a>>, VendorPrefix<'a>),
    "border-image-source": BorderImageSource(Box<'a, Image<'a>>),
    "border-image-outset": BorderImageOutset(Box<'a, RectFor_LengthOrNumber<'a>>),
    "border-image-repeat": BorderImageRepeat(Box<'a, BorderImageRepeat>),
    "border-image-width": BorderImageWidth(Box<'a, RectFor_BorderImageSideWidth<'a>>),
    "border-image-slice": BorderImageSlice(Box<'a, BorderImageSlice<'a>>),
    "border-image": BorderImage(Box<'a, BorderImage<'a>>, VendorPrefix<'a>),
    "border-color": BorderColor(Box<'a, BorderColor<'a>>),
    "border-style": BorderStyle(Box<'a, BorderStyle>),
    "border-width": BorderWidth(Box<'a, BorderWidth<'a>>),
    "border-block-color": BorderBlockColor(Box<'a, BorderBlockColor<'a>>),
    "border-block-style": BorderBlockStyle(Box<'a, BorderBlockStyle>),
    "border-block-width": BorderBlockWidth(Box<'a, BorderBlockWidth<'a>>),
    "border-inline-color": BorderInlineColor(Box<'a, BorderInlineColor<'a>>),
    "border-inline-style": BorderInlineStyle(Box<'a, BorderInlineStyle>),
    "border-inline-width": BorderInlineWidth(Box<'a, BorderInlineWidth<'a>>),
    "border": Border(Box<'a, GenericBorderFor_LineStyle<'a>>),
    "border-top": BorderTop(Box<'a, GenericBorderFor_LineStyle<'a>>),
    "border-bottom": BorderBottom(Box<'a, GenericBorderFor_LineStyle<'a>>),
    "border-left": BorderLeft(Box<'a, GenericBorderFor_LineStyle<'a>>),
    "border-right": BorderRight(Box<'a, GenericBorderFor_LineStyle<'a>>),
    "border-block": BorderBlock(Box<'a, GenericBorderFor_LineStyle<'a>>),
    "border-block-start": BorderBlockStart(Box<'a, GenericBorderFor_LineStyle<'a>>),
    "border-block-end": BorderBlockEnd(Box<'a, GenericBorderFor_LineStyle<'a>>),
    "border-inline": BorderInline(Box<'a, GenericBorderFor_LineStyle<'a>>),
    "border-inline-start": BorderInlineStart(Box<'a, GenericBorderFor_LineStyle<'a>>),
    "border-inline-end": BorderInlineEnd(Box<'a, GenericBorderFor_LineStyle<'a>>),
    "outline": Outline(Box<'a, GenericBorderFor_OutlineStyleAnd_11<'a>>),
    "outline-color": OutlineColor(Box<'a, CssColor<'a>>),
    "outline-style": OutlineStyle(Box<'a, OutlineStyle>),
    "outline-width": OutlineWidth(Box<'a, BorderSideWidth<'a>>),
    "flex-direction": FlexDirection(FlexDirection, VendorPrefix<'a>),
    "flex-wrap": FlexWrap(FlexWrap, VendorPrefix<'a>),
    "flex-flow": FlexFlow(Box<'a, FlexFlow>, VendorPrefix<'a>),
    "flex-grow": FlexGrow(f64, VendorPrefix<'a>),
    "flex-shrink": FlexShrink(f64, VendorPrefix<'a>),
    "flex-basis": FlexBasis(Box<'a, LengthPercentageOrAuto<'a>>, VendorPrefix<'a>),
    "flex": Flex(Box<'a, Flex<'a>>, VendorPrefix<'a>),
    "order": Order(f64, VendorPrefix<'a>),
    "align-content": AlignContent(Box<'a, AlignContent>, VendorPrefix<'a>),
    "justify-content": JustifyContent(Box<'a, JustifyContent>, VendorPrefix<'a>),
    "place-content": PlaceContent(Box<'a, PlaceContent<'a>>),
    "align-self": AlignSelf(Box<'a, AlignSelf>, VendorPrefix<'a>),
    "justify-self": JustifySelf(Box<'a, JustifySelf>),
    "place-self": PlaceSelf(Box<'a, PlaceSelf<'a>>),
    "align-items": AlignItems(Box<'a, AlignItems>, VendorPrefix<'a>),
    "justify-items": JustifyItems(Box<'a, JustifyItems>),
    "place-items": PlaceItems(Box<'a, PlaceItems<'a>>),
    "row-gap": RowGap(Box<'a, GapValue<'a>>),
    "column-gap": ColumnGap(Box<'a, GapValue<'a>>),
    "gap": Gap(Box<'a, Gap<'a>>),
    "box-orient": BoxOrient(BoxOrient, VendorPrefix<'a>),
    "box-direction": BoxDirection(BoxDirection, VendorPrefix<'a>),
    "box-ordinal-group": BoxOrdinalGroup(f64, VendorPrefix<'a>),
    "box-align": BoxAlign(BoxAlign, VendorPrefix<'a>),
    "box-flex": BoxFlex(f64, VendorPrefix<'a>),
    "box-flex-group": BoxFlexGroup(f64, VendorPrefix<'a>),
    "box-pack": BoxPack(BoxPack, VendorPrefix<'a>),
    "box-lines": BoxLines(BoxLines, VendorPrefix<'a>),
    "flex-pack": FlexPack(FlexPack, VendorPrefix<'a>),
    "flex-order": FlexOrder(f64, VendorPrefix<'a>),
    "flex-align": FlexAlign(BoxAlign, VendorPrefix<'a>),
    "flex-item-align": FlexItemAlign(FlexItemAlign, VendorPrefix<'a>),
    "flex-line-pack": FlexLinePack(FlexLinePack, VendorPrefix<'a>),
    "flex-positive": FlexPositive(f64, VendorPrefix<'a>),
    "flex-negative": FlexNegative(f64, VendorPrefix<'a>),
    "flex-preferred-size": FlexPreferredSize(Box<'a, LengthPercentageOrAuto<'a>>, VendorPrefix<'a>),
    "grid-template-columns": GridTemplateColumns(Box<'a, TrackSizing<'a>>),
    "grid-template-rows": GridTemplateRows(Box<'a, TrackSizing<'a>>),
    "grid-auto-columns": GridAutoColumns(Vec<'a, TrackSize<'a>>),
    "grid-auto-rows": GridAutoRows(Vec<'a, TrackSize<'a>>),
    "grid-auto-flow": GridAutoFlow(Box<'a, GridAutoFlow>),
    "grid-template-areas": GridTemplateAreas(Box<'a, GridTemplateAreas<'a>>),
    "grid-template": GridTemplate(Box<'a, GridTemplate<'a>>),
    "grid": Grid(Box<'a, Grid<'a>>),
    "grid-row-start": GridRowStart(Box<'a, GridLine<'a>>),
    "grid-row-end": GridRowEnd(Box<'a, GridLine<'a>>),
    "grid-column-start": GridColumnStart(Box<'a, GridLine<'a>>),
    "grid-column-end": GridColumnEnd(Box<'a, GridLine<'a>>),
    "grid-row": GridRow(Box<'a, GridRow<'a>>),
    "grid-column": GridColumn(Box<'a, GridColumn<'a>>),
    "grid-area": GridArea(Box<'a, GridArea<'a>>),
    "margin-top": MarginTop(Box<'a, LengthPercentageOrAuto<'a>>),
    "margin-bottom": MarginBottom(Box<'a, LengthPercentageOrAuto<'a>>),
    "margin-left": MarginLeft(Box<'a, LengthPercentageOrAuto<'a>>),
    "margin-right": MarginRight(Box<'a, LengthPercentageOrAuto<'a>>),
    "margin-block-start": MarginBlockStart(Box<'a, LengthPercentageOrAuto<'a>>),
    "margin-block-end": MarginBlockEnd(Box<'a, LengthPercentageOrAuto<'a>>),
    "margin-inline-start": MarginInlineStart(Box<'a, LengthPercentageOrAuto<'a>>),
    "margin-inline-end": MarginInlineEnd(Box<'a, LengthPercentageOrAuto<'a>>),
    "margin-block": MarginBlock(Box<'a, MarginBlock<'a>>),
    "margin-inline": MarginInline(Box<'a, MarginInline<'a>>),
    "margin": Margin(Box<'a, Margin<'a>>),
    "padding-top": PaddingTop(Box<'a, LengthPercentageOrAuto<'a>>),
    "padding-bottom": PaddingBottom(Box<'a, LengthPercentageOrAuto<'a>>),
    "padding-left": PaddingLeft(Box<'a, LengthPercentageOrAuto<'a>>),
    "padding-right": PaddingRight(Box<'a, LengthPercentageOrAuto<'a>>),
    "padding-block-start": PaddingBlockStart(Box<'a, LengthPercentageOrAuto<'a>>),
    "padding-block-end": PaddingBlockEnd(Box<'a, LengthPercentageOrAuto<'a>>),
    "padding-inline-start": PaddingInlineStart(Box<'a, LengthPercentageOrAuto<'a>>),
    "padding-inline-end": PaddingInlineEnd(Box<'a, LengthPercentageOrAuto<'a>>),
    "padding-block": PaddingBlock(Box<'a, PaddingBlock<'a>>),
    "padding-inline": PaddingInline(Box<'a, PaddingInline<'a>>),
    "padding": Padding(Box<'a, Padding<'a>>),
    "scroll-margin-top": ScrollMarginTop(Box<'a, LengthPercentageOrAuto<'a>>),
    "scroll-margin-bottom": ScrollMarginBottom(Box<'a, LengthPercentageOrAuto<'a>>),
    "scroll-margin-left": ScrollMarginLeft(Box<'a, LengthPercentageOrAuto<'a>>),
    "scroll-margin-right": ScrollMarginRight(Box<'a, LengthPercentageOrAuto<'a>>),
    "scroll-margin-block-start": ScrollMarginBlockStart(Box<'a, LengthPercentageOrAuto<'a>>),
    "scroll-margin-block-end": ScrollMarginBlockEnd(Box<'a, LengthPercentageOrAuto<'a>>),
    "scroll-margin-inline-start": ScrollMarginInlineStart(Box<'a, LengthPercentageOrAuto<'a>>),
    "scroll-margin-inline-end": ScrollMarginInlineEnd(Box<'a, LengthPercentageOrAuto<'a>>),
    "scroll-margin-block": ScrollMarginBlock(Box<'a, ScrollMarginBlock<'a>>),
    "scroll-margin-inline": ScrollMarginInline(Box<'a, ScrollMarginInline<'a>>),
    "scroll-margin": ScrollMargin(Box<'a, ScrollMargin<'a>>),
    "scroll-padding-top": ScrollPaddingTop(Box<'a, LengthPercentageOrAuto<'a>>),
    "scroll-padding-bottom": ScrollPaddingBottom(Box<'a, LengthPercentageOrAuto<'a>>),
    "scroll-padding-left": ScrollPaddingLeft(Box<'a, LengthPercentageOrAuto<'a>>),
    "scroll-padding-right": ScrollPaddingRight(Box<'a, LengthPercentageOrAuto<'a>>),
    "scroll-padding-block-start": ScrollPaddingBlockStart(Box<'a, LengthPercentageOrAuto<'a>>),
    "scroll-padding-block-end": ScrollPaddingBlockEnd(Box<'a, LengthPercentageOrAuto<'a>>),
    "scroll-padding-inline-start": ScrollPaddingInlineStart(Box<'a, LengthPercentageOrAuto<'a>>),
    "scroll-padding-inline-end": ScrollPaddingInlineEnd(Box<'a, LengthPercentageOrAuto<'a>>),
    "scroll-padding-block": ScrollPaddingBlock(Box<'a, ScrollPaddingBlock<'a>>),
    "scroll-padding-inline": ScrollPaddingInline(Box<'a, ScrollPaddingInline<'a>>),
    "scroll-padding": ScrollPadding(Box<'a, ScrollPadding<'a>>),
    "font-weight": FontWeight(Box<'a, FontWeight<'a>>),
    "font-size": FontSize(Box<'a, FontSize<'a>>),
    "font-stretch": FontStretch(Box<'a, FontStretch>),
    "font-family": FontFamily(Vec<'a, FontFamily<'a>>),
    "font-style": FontStyle(Box<'a, FontStyle<'a>>),
    "font-variant-caps": FontVariantCaps(FontVariantCaps),
    "line-height": LineHeight(Box<'a, LineHeight<'a>>),
    "font": Font(Box<'a, Font<'a>>),
    "vertical-align": VerticalAlign(Box<'a, VerticalAlign<'a>>),
    "font-palette": FontPalette(Box<'a, DashedIdentReference<'a>>),
    "transition-property": TransitionProperty(Vec<'a, PropertyId<'a>>, VendorPrefix<'a>),
    "transition-duration": TransitionDuration(Vec<'a, Time>, VendorPrefix<'a>),
    "transition-delay": TransitionDelay(Vec<'a, Time>, VendorPrefix<'a>),
    "transition-timing-function": TransitionTimingFunction(Vec<'a, EasingFunction>, VendorPrefix<'a>),
    "transition": Transition(Vec<'a, Transition<'a>>, VendorPrefix<'a>),
    "animation-name": AnimationName(Vec<'a, AnimationName<'a>>, VendorPrefix<'a>),
    "animation-duration": AnimationDuration(Vec<'a, Time>, VendorPrefix<'a>),
    "animation-timing-function": AnimationTimingFunction(Vec<'a, EasingFunction>, VendorPrefix<'a>),
    "animation-iteration-count": AnimationIterationCount(Vec<'a, AnimationIterationCount>, VendorPrefix<'a>),
    "animation-direction": AnimationDirection(Vec<'a, AnimationDirection>, VendorPrefix<'a>),
    "animation-play-state": AnimationPlayState(Vec<'a, AnimationPlayState>, VendorPrefix<'a>),
    "animation-delay": AnimationDelay(Vec<'a, Time>, VendorPrefix<'a>),
    "animation-fill-mode": AnimationFillMode(Vec<'a, AnimationFillMode>, VendorPrefix<'a>),
    "animation-composition": AnimationComposition(Vec<'a, AnimationComposition>),
    "animation-timeline": AnimationTimeline(Vec<'a, AnimationTimeline<'a>>),
    "animation-range-start": AnimationRangeStart(Vec<'a, AnimationRangeStart<'a>>),
    "animation-range-end": AnimationRangeEnd(Vec<'a, AnimationRangeEnd<'a>>),
    "animation-range": AnimationRange(Vec<'a, AnimationRange<'a>>),
    "animation": Animation(Vec<'a, Animation<'a>>, VendorPrefix<'a>),
    "transform": Transform(Vec<'a, Transform<'a>>, VendorPrefix<'a>),
    "transform-origin": TransformOrigin(Box<'a, Position<'a>>, VendorPrefix<'a>),
    "transform-style": TransformStyle(TransformStyle, VendorPrefix<'a>),
    "transform-box": TransformBox(TransformBox),
    "backface-visibility": BackfaceVisibility(BackfaceVisibility, VendorPrefix<'a>),
    "perspective": Perspective(Box<'a, Perspective<'a>>, VendorPrefix<'a>),
    "perspective-origin": PerspectiveOrigin(Box<'a, Position<'a>>, VendorPrefix<'a>),
    "translate": Translate(Box<'a, Translate<'a>>),
    "rotate": Rotate(Box<'a, Rotate<'a>>),
    "scale": Scale(Box<'a, Scale<'a>>),
    "text-transform": TextTransform(Box<'a, TextTransform>),
    "white-space": WhiteSpace(WhiteSpace),
    "tab-size": TabSize(Box<'a, LengthOrNumber<'a>>, VendorPrefix<'a>),
    "word-break": WordBreak(WordBreak),
    "line-break": LineBreak(LineBreak),
    "hyphens": Hyphens(Hyphens, VendorPrefix<'a>),
    "overflow-wrap": OverflowWrap(OverflowWrap),
    "word-wrap": WordWrap(OverflowWrap),
    "text-align": TextAlign(TextAlign),
    "text-align-last": TextAlignLast(TextAlignLast, VendorPrefix<'a>),
    "text-justify": TextJustify(TextJustify),
    "word-spacing": WordSpacing(Box<'a, Spacing<'a>>),
    "letter-spacing": LetterSpacing(Box<'a, Spacing<'a>>),
    "text-indent": TextIndent(Box<'a, TextIndent<'a>>),
    "text-decoration-line": TextDecorationLine(Box<'a, TextDecorationLine<'a>>, VendorPrefix<'a>),
    "text-decoration-style": TextDecorationStyle(TextDecorationStyle, VendorPrefix<'a>),
    "text-decoration-color": TextDecorationColor(Box<'a, CssColor<'a>>, VendorPrefix<'a>),
    "text-decoration-thickness": TextDecorationThickness(Box<'a, TextDecorationThickness<'a>>),
    "text-decoration": TextDecoration(Box<'a, TextDecoration<'a>>, VendorPrefix<'a>),
    "text-decoration-skip-ink": TextDecorationSkipInk(TextDecorationSkipInk, VendorPrefix<'a>),
    "text-emphasis-style": TextEmphasisStyle(Box<'a, TextEmphasisStyle<'a>>, VendorPrefix<'a>),
    "text-emphasis-color": TextEmphasisColor(Box<'a, CssColor<'a>>, VendorPrefix<'a>),
    "text-emphasis": TextEmphasis(Box<'a, TextEmphasis<'a>>, VendorPrefix<'a>),
    "text-emphasis-position": TextEmphasisPosition(Box<'a, TextEmphasisPosition>, VendorPrefix<'a>),
    "text-shadow": TextShadow(Vec<'a, TextShadow<'a>>),
    "text-size-adjust": TextSizeAdjust(Box<'a, TextSizeAdjust>, VendorPrefix<'a>),
    "direction": Direction(Direction2),
    "unicode-bidi": UnicodeBidi(UnicodeBidi),
    "box-decoration-break": BoxDecorationBreak(BoxDecorationBreak, VendorPrefix<'a>),
    "resize": Resize(Resize),
    "cursor": Cursor(Box<'a, Cursor<'a>>),
    "caret-color": CaretColor(Box<'a, ColorOrAuto<'a>>),
    "caret-shape": CaretShape(CaretShape),
    "caret": Caret(Box<'a, Caret<'a>>),
    "user-select": UserSelect(UserSelect, VendorPrefix<'a>),
    "accent-color": AccentColor(Box<'a, ColorOrAuto<'a>>),
    "appearance": Appearance(Box<'a, Appearance<'a>>, VendorPrefix<'a>),
    "list-style-type": ListStyleType(Box<'a, ListStyleType<'a>>),
    "list-style-image": ListStyleImage(Box<'a, Image<'a>>),
    "list-style-position": ListStylePosition(ListStylePosition),
    "list-style": ListStyle(Box<'a, ListStyle<'a>>),
    "marker-side": MarkerSide(MarkerSide),
    "composes": Composes(Box<'a, Composes<'a>>),
    "fill": Fill(Box<'a, SVGPaint<'a>>),
    "fill-rule": FillRule(FillRule),
    "fill-opacity": FillOpacity(f64),
    "stroke": Stroke(Box<'a, SVGPaint<'a>>),
    "stroke-opacity": StrokeOpacity(f64),
    "stroke-width": StrokeWidth(Box<'a, DimensionPercentageFor_LengthValue<'a>>),
    "stroke-linecap": StrokeLinecap(StrokeLinecap),
    "stroke-linejoin": StrokeLinejoin(StrokeLinejoin),
    "stroke-miterlimit": StrokeMiterlimit(f64),
    "stroke-dasharray": StrokeDasharray(Box<'a, StrokeDasharray<'a>>),
    "stroke-dashoffset": StrokeDashoffset(Box<'a, DimensionPercentageFor_LengthValue<'a>>),
    "marker-start": MarkerStart(Box<'a, Marker<'a>>),
    "marker-mid": MarkerMid(Box<'a, Marker<'a>>),
    "marker-end": MarkerEnd(Box<'a, Marker<'a>>),
    "marker": Marker(Box<'a, Marker<'a>>),
    "color-interpolation": ColorInterpolation(ColorInterpolation),
    "color-interpolation-filters": ColorInterpolationFilters(ColorInterpolation),
    "color-rendering": ColorRendering(ColorRendering),
    "shape-rendering": ShapeRendering(ShapeRendering),
    "text-rendering": TextRendering(TextRendering),
    "image-rendering": ImageRendering(ImageRendering),
    "clip-path": ClipPath(Box<'a, ClipPath<'a>>, VendorPrefix<'a>),
    "clip-rule": ClipRule(FillRule),
    "mask-image": MaskImage(Vec<'a, Image<'a>>, VendorPrefix<'a>),
    "mask-mode": MaskMode(Vec<'a, MaskMode>),
    "mask-repeat": MaskRepeat(Vec<'a, BackgroundRepeat>, VendorPrefix<'a>),
    "mask-position-x": MaskPositionX(Vec<'a, PositionComponentFor_HorizontalPositionKeyword<'a>>),
    "mask-position-y": MaskPositionY(Vec<'a, PositionComponentFor_VerticalPositionKeyword<'a>>),
    "mask-position": MaskPosition(Vec<'a, Position<'a>>, VendorPrefix<'a>),
    "mask-clip": MaskClip(Vec<'a, MaskClip>, VendorPrefix<'a>),
    "mask-origin": MaskOrigin(Vec<'a, GeometryBox>, VendorPrefix<'a>),
    "mask-size": MaskSize(Vec<'a, BackgroundSize<'a>>, VendorPrefix<'a>),
    "mask-composite": MaskComposite(Vec<'a, MaskComposite>),
    "mask-type": MaskType(MaskType),
    "mask": Mask(Vec<'a, Mask<'a>>, VendorPrefix<'a>),
    "mask-border-source": MaskBorderSource(Box<'a, Image<'a>>),
    "mask-border-mode": MaskBorderMode(MaskBorderMode),
    "mask-border-slice": MaskBorderSlice(Box<'a, BorderImageSlice<'a>>),
    "mask-border-width": MaskBorderWidth(Box<'a, RectFor_BorderImageSideWidth<'a>>),
    "mask-border-outset": MaskBorderOutset(Box<'a, RectFor_LengthOrNumber<'a>>),
    "mask-border-repeat": MaskBorderRepeat(Box<'a, BorderImageRepeat>),
    "mask-border": MaskBorder(Box<'a, MaskBorder<'a>>),
    "-webkit-mask-composite": WebKitMaskComposite(Vec<'a, WebKitMaskComposite<'a>>),
    "mask-source-type": WebKitMaskSourceType(Vec<'a, WebKitMaskSourceType>, VendorPrefix<'a>),
    "mask-box-image": WebKitMaskBoxImage(Box<'a, BorderImage<'a>>, VendorPrefix<'a>),
    "mask-box-image-source": WebKitMaskBoxImageSource(Box<'a, Image<'a>>, VendorPrefix<'a>),
    "mask-box-image-slice": WebKitMaskBoxImageSlice(Box<'a, BorderImageSlice<'a>>, VendorPrefix<'a>),
    "mask-box-image-width": WebKitMaskBoxImageWidth(Box<'a, RectFor_BorderImageSideWidth<'a>>, VendorPrefix<'a>),
    "mask-box-image-outset": WebKitMaskBoxImageOutset(Box<'a, RectFor_LengthOrNumber<'a>>, VendorPrefix<'a>),
    "mask-box-image-repeat": WebKitMaskBoxImageRepeat(Box<'a, BorderImageRepeat>, VendorPrefix<'a>),
    "filter": Filter(Box<'a, FilterList<'a>>, VendorPrefix<'a>),
    "backdrop-filter": BackdropFilter(Box<'a, FilterList<'a>>, VendorPrefix<'a>),
    "mix-blend-mode": MixBlendMode(BlendMode),
    "z-index": ZIndex(Box<'a, ZIndex>),
    "container-type": ContainerType(ContainerType),
    "container-name": ContainerName(Box<'a, ContainerNameList<'a>>),
    "container": Container(Box<'a, Container<'a>>),
    "view-transition-name": ViewTransitionName(Box<'a, ViewTransitionName<'a>>),
    "view-transition-class": ViewTransitionClass(Box<'a, NoneOrCustomIdentList<'a>>),
    "view-transition-group": ViewTransitionGroup(Box<'a, ViewTransitionGroup<'a>>),
    "color-scheme": ColorScheme(Box<'a, ColorScheme>),
    "print-color-adjust": PrintColorAdjust(PrintColorAdjust, VendorPrefix<'a>),
}
