use std::{
    cell::UnsafeCell,
    fmt,
    marker::{PhantomData, PhantomPinned},
    pin::Pin,
    rc::Rc,
};

use crate::boxed::Box;

/// An arena-owned, pinned [`GhostCell`].
pub type GhostBox<'a, 'ghost, T> = Pin<Box<'a, GhostCell<'ghost, T>>>;

pub(crate) type InvariantLifetime<'ghost> =
    PhantomData<fn(&'ghost mut &'ghost ()) -> &'ghost mut &'ghost ()>;

/// The unique mutation permission for a pool of [`GhostCell`] values.
///
/// The invariant `'ghost` brand is generated by [`GhostToken::scope`] and
/// cannot be named or reproduced by the caller.
///
/// A mutable borrow of the token prevents a second cell from being mutably
/// borrowed at the same time:
///
/// ```compile_fail
/// use rocketcss_allocator::{GhostCell, GhostToken};
///
/// GhostToken::scope(|mut token| {
///     let first = std::pin::pin!(GhostCell::new(1));
///     let second = std::pin::pin!(GhostCell::new(2));
///     let first = first.as_ref().borrow_mut(&mut token);
///     let second = second.as_ref().borrow_mut(&mut token);
///     *first += *second;
/// });
/// ```
///
/// Distinct token scopes cannot access the same cell:
///
/// ```compile_fail
/// use rocketcss_allocator::{GhostCell, GhostToken};
///
/// GhostToken::scope(|mut first_token| {
///     GhostToken::scope(|mut second_token| {
///         let cell = std::pin::pin!(GhostCell::new(1));
///         let first = cell.as_ref().borrow_mut(&mut first_token);
///         let second = cell.as_ref().borrow_mut(&mut second_token);
///         *first += *second;
///     });
/// });
/// ```
pub struct GhostToken<'ghost> {
    _brand: InvariantLifetime<'ghost>,
    _not_send_or_sync: PhantomData<Rc<()>>,
}

impl<'ghost> GhostToken<'ghost> {
    #[inline]
    fn branded() -> Self {
        Self {
            _brand: PhantomData,
            _not_send_or_sync: PhantomData,
        }
    }
}

impl GhostToken<'_> {
    /// Creates a fresh mutation brand and its unique token.
    #[inline]
    pub fn scope<R>(f: impl for<'ghost> FnOnce(GhostToken<'ghost>) -> R) -> R {
        f(GhostToken::branded())
    }
}

/// An aliasable value whose access is controlled by a matching [`GhostToken`].
#[repr(transparent)]
pub struct GhostCell<'ghost, T: ?Sized> {
    _brand: InvariantLifetime<'ghost>,
    _pin: PhantomPinned,
    value: UnsafeCell<T>,
}

impl<T: ?Sized> fmt::Debug for GhostCell<'_, T> {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_tuple("GhostCell")
            .field(&self.value.get())
            .finish()
    }
}

impl<T: PartialEq + ?Sized> PartialEq for GhostCell<'_, T> {
    #[inline]
    fn eq(&self, other: &Self) -> bool {
        if !std::ptr::eq(self.value.get(), other.value.get()) {
            return false;
        }
        // TODO: fix GhostCell Eq
        unsafe { (*self.value.get()).eq(&*other.value.get()) }
    }
}

impl<T: Eq + ?Sized> Eq for GhostCell<'_, T> {}

impl<'ghost, T> GhostCell<'ghost, T> {
    #[inline]
    pub fn new(value: T) -> Self {
        Self {
            _brand: PhantomData,
            _pin: PhantomPinned,
            value: UnsafeCell::new(value),
        }
    }
}

impl<'ghost, T: ?Sized> GhostCell<'ghost, T> {
    #[inline]
    pub fn borrow<'cell>(
        self: Pin<&'cell Self>,
        _token: &'cell GhostToken<'ghost>,
    ) -> Pin<&'cell T> {
        // SAFETY: shared access requires a shared borrow of the unique token.
        // A mutable borrow of any cell with this brand requires an exclusive
        // borrow of that same token. The value is structurally pinned with its
        // GhostCell.
        unsafe { Pin::new_unchecked(&*self.get_ref().value.get()) }
    }

    #[inline]
    pub fn borrow_mut<'cell>(
        self: Pin<&'cell Self>,
        _token: &'cell mut GhostToken<'ghost>,
    ) -> Pin<&'cell mut T> {
        // SAFETY: the returned borrow keeps the unique token exclusively
        // borrowed, preventing access to every other cell with this brand.
        // The value is structurally pinned with its GhostCell.
        unsafe { Pin::new_unchecked(&mut *self.get_ref().value.get()) }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn one_token_mutates_multiple_cells_sequentially() {
        GhostToken::scope(|mut token| {
            let first = std::pin::pin!(GhostCell::new(1));
            let second = std::pin::pin!(GhostCell::new(2));

            *first.as_ref().borrow_mut(&mut token) += 10;
            *second.as_ref().borrow_mut(&mut token) += 20;

            assert_eq!(*first.as_ref().borrow(&token), 11);
            assert_eq!(*second.as_ref().borrow(&token), 22);
        });
    }

    #[test]
    fn multiple_shared_borrows_can_coexist() {
        GhostToken::scope(|token| {
            let first = std::pin::pin!(GhostCell::new(1));
            let second = std::pin::pin!(GhostCell::new(2));
            let first = first.as_ref().borrow(&token);
            let second = second.as_ref().borrow(&token);

            assert_eq!(*first + *second, 3);
        });
    }

    #[test]
    fn arena_ast_stores_only_branded_cell_references() {
        struct AstNode<'a, 'ghost> {
            previous: Option<crate::Ref<'a, 'ghost, AstNode<'a, 'ghost>>>,
            value: u32,
        }

        let allocator = crate::Allocator::new();
        allocator.with_ghost(|mut token| {
            let first = allocator.alloc_ghost(AstNode {
                previous: None,
                value: 1,
            });
            let first_ref = crate::Ref::from(&first);
            let second = allocator.alloc_ghost(AstNode {
                previous: Some(first_ref),
                value: 2,
            });

            first.as_ref().borrow_mut(&mut token).value += 10;
            second.as_ref().borrow_mut(&mut token).value += 20;

            let second = second.as_ref().borrow(&token);
            assert_eq!(second.value, 22);
            assert_eq!(second.previous.unwrap().get(&token).value, 11);
        });
    }
}
