use std::{cell::UnsafeCell, fmt, marker::PhantomData, rc::Rc};

type InvariantLifetime<'ghost> = PhantomData<fn(&'ghost mut &'ghost ()) -> &'ghost mut &'ghost ()>;

/// The unique mutation permission for a pool of [`GhostCell`] values.
///
/// The invariant `'ghost` brand is generated by [`GhostToken::scope`] and
/// cannot be named or reproduced by the caller.
///
/// A mutable borrow of the token prevents a second cell from being mutably
/// borrowed at the same time:
///
/// ```compile_fail
/// use rocketcss_allocator::{GhostCell, GhostToken};
///
/// GhostToken::scope(|mut token| {
///     let first = GhostCell::new(1);
///     let second = GhostCell::new(2);
///     let first = first.borrow_mut(&mut token);
///     let second = second.borrow_mut(&mut token);
///     *first += *second;
/// });
/// ```
pub struct GhostToken<'ghost> {
    _brand: InvariantLifetime<'ghost>,
    _not_send_or_sync: PhantomData<Rc<()>>,
}

impl<'ghost> GhostToken<'ghost> {
    #[inline]
    pub(crate) fn branded() -> Self {
        Self {
            _brand: PhantomData,
            _not_send_or_sync: PhantomData,
        }
    }
}

impl GhostToken<'_> {
    /// Creates a fresh mutation brand and its unique token.
    #[inline]
    pub fn scope<R>(f: impl for<'ghost> FnOnce(GhostToken<'ghost>) -> R) -> R {
        f(GhostToken::branded())
    }
}

/// An aliasable value whose access is controlled by a matching [`GhostToken`].
#[repr(transparent)]
pub struct GhostCell<'ghost, T: ?Sized> {
    _brand: InvariantLifetime<'ghost>,
    value: UnsafeCell<T>,
}

impl<T: ?Sized> fmt::Debug for GhostCell<'_, T> {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_tuple("GhostCell")
            .field(&self.value.get())
            .finish()
    }
}

impl<'ghost, T> GhostCell<'ghost, T> {
    #[inline]
    pub const fn new(value: T) -> Self {
        Self {
            _brand: PhantomData,
            value: UnsafeCell::new(value),
        }
    }

    #[inline]
    pub fn into_inner(self) -> T {
        self.value.into_inner()
    }
}

impl<'ghost, T: ?Sized> GhostCell<'ghost, T> {
    #[inline]
    pub fn borrow<'cell>(&'cell self, _token: &'cell GhostToken<'ghost>) -> &'cell T {
        // SAFETY: shared access requires a shared borrow of the unique token.
        // A mutable borrow of any cell with this brand requires an exclusive
        // borrow of that same token.
        unsafe { &*self.value.get() }
    }

    #[inline]
    pub fn borrow_mut<'cell>(&'cell self, _token: &'cell mut GhostToken<'ghost>) -> &'cell mut T {
        // SAFETY: the returned borrow keeps the unique token exclusively
        // borrowed, preventing access to every other cell with this brand.
        unsafe { &mut *self.value.get() }
    }

    #[inline]
    pub fn get_mut(&mut self) -> &mut T {
        self.value.get_mut()
    }
}

impl<T: Default> Default for GhostCell<'_, T> {
    #[inline]
    fn default() -> Self {
        Self::new(T::default())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn one_token_mutates_multiple_cells_sequentially() {
        GhostToken::scope(|mut token| {
            let first = GhostCell::new(1);
            let second = GhostCell::new(2);

            *first.borrow_mut(&mut token) += 10;
            *second.borrow_mut(&mut token) += 20;

            assert_eq!(*first.borrow(&token), 11);
            assert_eq!(*second.borrow(&token), 22);
        });
    }

    #[test]
    fn multiple_shared_borrows_can_coexist() {
        GhostToken::scope(|token| {
            let first = GhostCell::new(1);
            let second = GhostCell::new(2);
            let first = first.borrow(&token);
            let second = second.borrow(&token);

            assert_eq!(*first + *second, 3);
        });
    }

    #[test]
    fn arena_ast_stores_only_branded_cell_references() {
        struct AstNode<'a, 'ghost> {
            previous:
                Option<&'a GhostCell<'ghost, AstNode<'a, 'ghost>>>,
            value: u32,
        }

        let allocator = crate::Allocator::new();
        allocator.with_ghost(|mut token| {
            let first = allocator.alloc_ghost(AstNode {
                previous: None,
                value: 1,
            });
            let second = allocator.alloc_ghost(AstNode {
                previous: Some(first),
                value: 2,
            });

            first.borrow_mut(&mut token).value += 10;
            second.borrow_mut(&mut token).value += 20;

            let second = second.borrow(&token);
            assert_eq!(second.value, 22);
            assert_eq!(second.previous.unwrap().borrow(&token).value, 11);
        });
    }
}
