use std::{fmt, marker::PhantomData, ptr::NonNull, rc::Rc};

type InvariantLifetime<'ghost> = PhantomData<fn(&'ghost mut &'ghost ()) -> &'ghost mut &'ghost ()>;

/// The unique mutation permission for a pool of [`GhostCell`] values.
///
/// The invariant `'ghost` brand is generated by [`GhostToken::scope`] and
/// cannot be named or reproduced by the caller.
///
/// A mutable borrow of the token prevents a second cell from being mutably
/// borrowed at the same time:
///
/// ```compile_fail
/// use rocketcss_allocator::{GhostCell, GhostToken};
///
/// GhostToken::scope(|mut token| {
///     let mut first_value = 1;
///     let mut second_value = 2;
///     let first = GhostCell::from_mut(&mut first_value);
///     let second = GhostCell::from_mut(&mut second_value);
///     let first = first.borrow_mut(&mut token);
///     let second = second.borrow_mut(&mut token);
///     *first += *second;
/// });
/// ```
///
/// Distinct token scopes cannot access the same cell:
///
/// ```compile_fail
/// use rocketcss_allocator::{GhostCell, GhostToken};
///
/// GhostToken::scope(|mut first_token| {
///     GhostToken::scope(|mut second_token| {
///         let mut value = 1;
///         let cell = GhostCell::from_mut(&mut value);
///         let first = cell.borrow_mut(&mut first_token);
///         let second = cell.borrow_mut(&mut second_token);
///         *first += *second;
///     });
/// });
/// ```
pub struct GhostToken<'ghost> {
    _brand: InvariantLifetime<'ghost>,
    _not_send_or_sync: PhantomData<Rc<()>>,
}

impl<'ghost> GhostToken<'ghost> {
    #[inline]
    pub(crate) fn branded() -> Self {
        Self {
            _brand: PhantomData,
            _not_send_or_sync: PhantomData,
        }
    }
}

impl GhostToken<'_> {
    /// Creates a fresh mutation brand and its unique token.
    #[inline]
    pub fn scope<R>(f: impl for<'ghost> FnOnce(GhostToken<'ghost>) -> R) -> R {
        f(GhostToken::branded())
    }
}

/// An aliasable value whose access is controlled by a matching [`GhostToken`].
#[repr(transparent)]
pub struct GhostCell<'a, 'ghost, T: ?Sized> {
    pointer: NonNull<T>,
    _target: PhantomData<&'a mut T>,
    _brand: InvariantLifetime<'ghost>,
}

impl<T: ?Sized> Clone for GhostCell<'_, '_, T> {
    #[inline]
    fn clone(&self) -> Self {
        *self
    }
}

impl<T: ?Sized> Copy for GhostCell<'_, '_, T> {}

impl<T: ?Sized> fmt::Debug for GhostCell<'_, '_, T> {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_tuple("GhostCell")
            .field(&self.pointer)
            .finish()
    }
}

impl<T: ?Sized> PartialEq for GhostCell<'_, '_, T> {
    #[inline]
    fn eq(&self, other: &Self) -> bool {
        std::ptr::eq(self.pointer.as_ptr(), other.pointer.as_ptr())
    }
}

impl<T: ?Sized> Eq for GhostCell<'_, '_, T> {}

impl<'a, 'ghost, T: ?Sized> GhostCell<'a, 'ghost, T> {
    #[inline]
    pub fn from_mut(value: &'a mut T) -> Self {
        Self {
            pointer: NonNull::from(value),
            _target: PhantomData,
            _brand: PhantomData,
        }
    }

    #[inline]
    pub(crate) unsafe fn from_raw(pointer: NonNull<T>) -> Self {
        Self {
            pointer,
            _target: PhantomData,
            _brand: PhantomData,
        }
    }

    #[inline]
    pub fn borrow<'cell>(&self, _token: &'cell GhostToken<'ghost>) -> &'cell T
    where
        'a: 'cell,
    {
        // SAFETY: shared access requires a shared borrow of the unique token.
        // A mutable borrow of any cell with this brand requires an exclusive
        // borrow of that same token.
        unsafe { self.pointer.as_ref() }
    }

    #[inline]
    pub fn borrow_mut<'cell>(&self, _token: &'cell mut GhostToken<'ghost>) -> &'cell mut T
    where
        'a: 'cell,
    {
        // SAFETY: the returned borrow keeps the unique token exclusively
        // borrowed, preventing access to every other cell with this brand.
        unsafe { &mut *self.pointer.as_ptr() }
    }

    #[inline]
    pub(crate) fn pointer(&self) -> NonNull<T> {
        self.pointer
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn one_token_mutates_multiple_cells_sequentially() {
        GhostToken::scope(|mut token| {
            let mut first_value = 1;
            let mut second_value = 2;
            let first = GhostCell::from_mut(&mut first_value);
            let second = GhostCell::from_mut(&mut second_value);

            *first.borrow_mut(&mut token) += 10;
            *second.borrow_mut(&mut token) += 20;

            assert_eq!(*first.borrow(&token), 11);
            assert_eq!(*second.borrow(&token), 22);
        });
    }

    #[test]
    fn multiple_shared_borrows_can_coexist() {
        GhostToken::scope(|token| {
            let mut first_value = 1;
            let mut second_value = 2;
            let first = GhostCell::from_mut(&mut first_value);
            let second = GhostCell::from_mut(&mut second_value);
            let first = first.borrow(&token);
            let second = second.borrow(&token);

            assert_eq!(*first + *second, 3);
        });
    }

    #[test]
    fn arena_ast_stores_only_branded_cell_references() {
        struct AstNode<'a, 'ghost> {
            previous: Option<&'a GhostCell<'a, 'ghost, AstNode<'a, 'ghost>>>,
            value: u32,
        }

        let allocator = crate::Allocator::new();
        allocator.with_ghost(|mut token| {
            let first = allocator.alloc_ghost(AstNode {
                previous: None,
                value: 1,
            });
            let second = allocator.alloc_ghost(AstNode {
                previous: Some(first),
                value: 2,
            });

            first.borrow_mut(&mut token).value += 10;
            second.borrow_mut(&mut token).value += 20;

            let second = second.borrow(&token);
            assert_eq!(second.value, 22);
            assert_eq!(second.previous.unwrap().borrow(&token).value, 11);
        });
    }
}
